---
- name: Install Snapd
  dnf:
    name: snapd 
    state: latest
  become: yes
# tasks file for snapd
#
- name: Create the snapd symbolic link
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: yes
