---
# tasks file for ansible_zsh
- name: Install the ZSH package
  dnf:
    name: zsh
    state: latest
  become: true 

- name: Install TMUX
  dnf:
    name: TMUX
    state: latest
  become: true

- name: Install TMUX settings
  ansible.builtin.template:
    src: "tmux.conf.j2"
    dest: ~/.tmux.conf
    owner: myork
    group: myork
    mode: '0644'

- name: Download the OhMyZSH install script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: /tmp/install.sh
    mode: "0755"

- name: Run the installer
  ansible.builtin.command:
    cmd: /tmp/install.sh
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh"
  ignore_errors: true

- name: Set the ZSH theme
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: ^(ZSH_THEME=).*
    line: '\g<1>{{ zsh_theme }}'
    backrefs: yes

- name: "Update the {{ lookup('ansible.builtin.env', 'USER') }} user to use th ZSH shell"
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: /usr/bin/zsh
  become: true

# TODO: Paramaterise this when you get time

- name: "Insert the bin directories for the local user"
  lineinfile:
    path: '~/.zshrc'
    regexp: '^export PATH='
    line: "export PATH={{ zsh_path }}"
    # line: 'export PATH=$HOME/bin:/usr/local/bin:~/.local/bin:$PATH'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: /home/myork/omtmux 

- name: Copy the omtmux config into ~/.config/tmux  
  ansible.builtin.copy:
    src: /home/myork/omtmux/.tmux.conf.local
    dest: /home/myork/.config/tmux/tmux.conf.local
    owner: myork
    group: myork
    mode: '0644'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /home/myork/.config/tmux/tmux.conf.local
    dest: /home/myork/.config/tmux/tmux.conf
    owner: myork
    group: myork 
    state: link
    force: true 